name: Possible new production release

on:
  push:
    branches:
      - preview

jobs:
  check-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout preview branch
        uses: actions/checkout@v2
        with:
          ref: preview

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check if main is behind preview
        id: check
        run: |
          MAIN_REV=$(git rev-parse origin/main)
          PREVIEW_REV=$(git rev-parse HEAD)
          if [ $(git merge-base origin/main HEAD) != $MAIN_REV ]; then
            echo "::set-output name=behind::true"
          else
            echo "::set-output name=behind::false"
          fi

      - name: Send Discord notification
        if: steps.check.outputs.behind == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The main branch is behind the preview branch in the repository {{ github.repository }}."
